name: ci

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
      - 'feature/**'

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm install

      - name: Run linter 👀
        run: npm run lint